### ISSUE TITLE
NIST wrapper would be better included as a dependency

### ISSUE THREAD

**Issue by ccurtis7** [raman-noodles/Raman-noodles#1]
I noticed that you grabbed the webbook wrapper from [here](https://github.com/subpath/NIST_chemistry_webbook_wrapper). While it is open source, it might be better to include it as a dependency rather than copying the code into your own repo. Best practices and all.

**Comment by JonathanOnorato** [comment]
Hi @ccurtis7, thanks for the feedback. Ultimately, we had only copied the code as we were looking to get an idea of how it worked, and to play around with it to see if it met our needs. Ultimately, we decided not to use that package, but we didn't want to delete it outright in case we wanted to look at it again. It had some issues with its functionality, and it was not being supported at all, so we didn't want to rely on it. I'm not sure if there's a good way to acknowledge in our repo structure that we are not using the code, but if so, we would be happy to make those changes.
