### ISSUE TITLE
Project pre-review

### ISSUE THREAD

**Issue by dacb** [raman-noodles/Raman-noodles#12]
A few things I noticed:

- [x] There is a lot of "cruft" in your repo.  Directories that are not clearly labeled, e.g. the matlab code. There are two ways to deal with these.  One is to make sub directories like "prior_art" or "development" and another is to put an annotated directory structure in your README.md by running `tree` and adding comment lines and putting it in a markdown code block.  Get those example notebooks into the examples directory.  Make a doc directory that contains your use cases, component sketch, tech review presentation, and final poster.

- [x] Your tests are pretty weak.  Or at least they appear that way.  One thing that would help with this is to add some docstrings to the tests that state how the tests actually provide a test of the system.  They seem to be "smoke tests" that check if something explodes but don't actually check if the output / result is correct.

- [x] I dig the wiki - finish it!

- [x] Great use of issues.

Overall looking good!

**Comment by erasmuss** [comment]
This is either being worked on or finished - should be all good by the Friday morning deadline.
