### ISSUE TITLE
Store raw data on local machines and don't upload to Github

### ISSUE THREAD

**Issue by ccurtis7** [raman-noodles/Raman-noodles#2]
It's usually a good idea to not upload data to Gihub (data files can be really large and take up space, it's a good idea to separate datasets from code, many datasets aren't open source and have their own separate license, etc).

You can usually store the datasets in your local repo still. Just add the file extension of your data files to your .gitignore file (in your case, .jdx would be a good one) so that Git skips them when you type `git status`.

**Comment by JonathanOnorato** [comment]
Hi @ccurtis7, I've included Parker on this in case he needs to correct me, but we've decided to use Google's Team Drives to host our data. We're currently storing the data in the repo here to make it a bit more easily accessible for all of us, but once we implement the google drive link, it should become unnecessary. I think it might be a good point that it would be of value to allow the user the option to import their data from a Google Drive location, or from a computer file system. I'm not sure we'll be implementing that prior to the end of the quarter, but maybe for next quarter when we continue this project we can investigate this.

**Comment by ParkerSteichen** [comment]
I have a couple ideas of how we separate the data and the code. Downloading a small number of spectra (even up to 100) looks like it won't take much time at all so perhaps we can improve our data download wrapper (shoyu.py) to include a initialize_standard_library function that will automatically download the "standard library" from NIST to the users local directory when they first use the software. Then they can continue to use the wrapper to add spectra as needed. This way our code wouldn't contain the data itself, just a list/dictionary of CAS registry numbers for the spectra we think would be appropriate for a "standard library".

**Comment by ParkerSteichen** [comment]
We opted to go with the "standard library" approach. When the software is installed the user will first need to run the shoyu.initialize_standard_library() function which will download a set of raman spectra from the NIST Chemistry WebBook. In the future we may incorporate this into the installation process.
