### ISSUE TITLE
Some path errors and dictionary overwrite problems occur when running shoyu_example.ipynb.

### ISSUE THREAD

**Issue by JunLin615** [raman-noodles/Raman-noodles#20]
Thank you very much for your work.Raman Noodles is great.

I don't know if I'm the only one who has a problem running shoyu_example.ipynb. Therefore,I read shoyu.py after I met the mistake.It turns out that these errors are all related to the function add_jdx.So I changed line 74 ‘'raman_spectra/shoyu_data_dict.p'’ in  shoyu.py to '../raman_spectra/shoyu_data_dict.p' to fix the problem I encountered running shoyu_example.ipynb.I hope my advice will be helpful

Thank you again for your work

**Comment by erasmuss** [comment]
HI @JunLin615 thanks for teh encouragement and comments. This repo was completed a while ago - I will make the changes that you suggested and make sure that works. Thanks again!
