### ISSUE TITLE
IF statement needed in Shoyu.py

### ISSUE THREAD

**Issue by JonathanOnorato** [raman-noodles/Raman-noodles#5]
The shoyu.py function states that it is downloading a spectra, even if the spectra has already been downloaded. Should be fixable with a simple IF statement, or by changing some structure.

**Comment by JonathanOnorato** [comment]
I slightly misunderstood the wording of a print statement, so the issue description was not actually that accurate. I thought, for example, that when the statement "WATER added to shoyu_data_dict.p" was being written, that it was implying that the WATER spectra was being downloaded. I realize that instead that was a statement that was loading the WATER spectra from the file folder into a dictionary. I updated the wording of the print statement to be more clear.

**Comment by ParkerSteichen** [comment]
Jon I think I deleted the version of shoyu.py that you updated the string in. You will need to make the change again. Sorry. Conflicts like this is why I tried to only have one copy of shoyu in the repo

**Comment by JonathanOnorato** [comment]
The file was deleted, but the shoyu.py file has been re-updated with clarifying text.
