### ISSUE TITLE
New Function - After Data Import, Before Data Fit

### ISSUE THREAD

**Issue by JonathanOnorato** [raman-noodles/Raman-noodles#7]
An idea that might be a good call. In the function for add_jdx, we could take the data from the y['abs'] column and check to make sure it is normalized. Basically, we could do something to the effect of y['abs'].max() > 1.05, then just divide the whole list of values by y['abs'].max(). Not a burning problem, but would be a nice thing to implement. It would definitely need to come after baselining the data, but it could be a nice easy thing to do, that would be helpful for a number of people.

**Comment by erasmuss** [comment]
not needed, will back log for later.
